name: Update Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Update RubyGems
        run: gem update --system

      - name: Pull in my posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://yexuhang.com/feed.xml"
          max_post_count: 5
          date_format: "mmm d, yyyy"
          template: "<tr><td>$title</td><td>$url</td></tr>"