name: Update Blog Posts

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in my posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://yexuhang.com/feed.xml"
          max_post_count: 3
          template: "<tr><td>$title</td><td>$url</td></tr>"